---
name: "package-app"

on:
  push:
    branches:
      - main

env:
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  tagged-release:
    name: "Package App"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rename app
        run: |
          mv app ${APP_NAME}
      - name: Create spl
        run: |
          COPYFILE_DISABLE=1 tar -cvzf ${APP_NAME}.spl ${APP_NAME}
      - name: Release spl
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            *.spl
